# Generated by Django 4.2.21 on 2025-05-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedtogoal',
            name='monthly_pay',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
