# Generated by Django 4.2.21 on 2025-05-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedtogoal',
            name='current_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
