# Generated by Django 4.2.21 on 2025-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_connectedtogoal_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deposit_target_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='saving_target_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='total_target_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
