# Generated by Django 4.2.21 on 2025-05-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_additionaloption_come_from_and_more'),
        ('goals', '0003_alter_goal_deposit_target_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedtogoal',
            name='additionoption_product',
        ),
        migrations.RemoveField(
            model_name='connectedtogoal',
            name='option_product',
        ),
        migrations.AddField(
            model_name='connectedtogoal',
            name='additionoptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_to_goal', to='finance.additionaloption'),
        ),
        migrations.AddField(
            model_name='connectedtogoal',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_to_goal', to='finance.option'),
        ),
        migrations.AlterField(
            model_name='connectedtogoal',
            name='additional_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_to_goal', to='finance.additionalproduct'),
        ),
        migrations.AlterField(
            model_name='connectedtogoal',
            name='financial_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_to_goal', to='finance.financialproduct'),
        ),
    ]
