# Generated by Django 4.2.21 on 2025-05-20 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('020000', '은행'), ('030300', '저축은행')], max_length=6)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('homepage_url', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('published_date', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=20)),
                ('product_type', models.CharField(choices=[('D', '예금'), ('S', '적금')], max_length=5)),
                ('special_condition', models.TextField(blank=True, null=True)),
                ('join_way', models.TextField()),
                ('end_interest_rate', models.FloatField()),
                ('join_deny', models.CharField(choices=[(1, '제한없음'), (2, '서민전용'), (3, '일부제한')], max_length=10)),
                ('join_member', models.CharField(max_length=50)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('product_start_date', models.DateField()),
                ('product_end_date', models.DateField(blank=True, null=True)),
                ('submit_date', models.DateTimeField()),
                ('financial_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financialcompany')),
            ],
        ),
        migrations.CreateModel(
            name='OptionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_type', models.CharField(max_length=5)),
                ('save_type_name', models.CharField(max_length=10)),
                ('reward_type', models.CharField(default='', max_length=5)),
                ('reward_type_name', models.CharField(default='', max_length=10)),
                ('save_month', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('max_interest_rate', models.FloatField()),
                ('finance_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('D', '예금'), ('S', '적금')], max_length=5)),
                ('special_condition', models.TextField(blank=True, null=True)),
                ('join_way', models.TextField()),
                ('end_interest_rate', models.FloatField()),
                ('join_deny', models.CharField(max_length=10)),
                ('join_member', models.CharField(max_length=20)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financialcompany')),
            ],
        ),
    ]
