# Generated by Django 4.2.21 on 2025-05-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='financial_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.financialcompany'),
        ),
        migrations.AlterField(
            model_name='option',
            name='financial_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance.financialproduct'),
        ),
    ]
