# Generated by Django 4.2.21 on 2025-05-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionproduct',
            name='reward_type_name',
        ),
        migrations.RemoveField(
            model_name='optionproduct',
            name='save_type_name',
        ),
        migrations.AlterField(
            model_name='financialcompany',
            name='homepage_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='optionproduct',
            name='reward_type',
            field=models.CharField(blank=True, choices=[('S', '정액적립식'), ('F', '자유적립식')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='optionproduct',
            name='save_type',
            field=models.CharField(choices=[('S', '단리'), ('M', '복리')], max_length=1),
        ),
    ]
