# Generated by Django 4.2.21 on 2025-05-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaloption',
            name='financial_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_option', to='finance.financialcompany'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='financial_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_option', to='finance.additionalproduct'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='financial_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product', to='finance.financialcompany'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='financial_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_product', to='finance.financialcompany'),
        ),
        migrations.AlterField(
            model_name='option',
            name='financial_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='finance.financialcompany'),
        ),
        migrations.AlterField(
            model_name='option',
            name='financial_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='finance.financialproduct'),
        ),
    ]
