# Generated by Django 4.2.21 on 2025-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_delete_spot_alter_additionaloption_come_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaloption',
            name='come_from',
            field=models.CharField(default='additional', max_length=10),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='come_from',
            field=models.CharField(default='additional', max_length=10),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='come_from',
            field=models.CharField(default='original', max_length=10),
        ),
        migrations.AlterField(
            model_name='option',
            name='come_from',
            field=models.CharField(default='original', max_length=10),
        ),
    ]
