# Generated by Django 4.2.21 on 2025-05-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_work',
        ),
        migrations.AddField(
            model_name='user',
            name='work_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
