# Generated by Django 4.2.21 on 2025-05-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_work_user_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assets',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
